version: '3'
services:
  web:
    build: .
    container_name: djangoapp
    ports:
    - "8000:5000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - db
    depends_on:
      - db
  django_migration:
    build: .
    container_name: djangoapp-migrations
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: djangoapp-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  logvolume01: {}
  data: {}
